// <auto-generated />
namespace DevbridgeSquares.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changenamingofSquareEnititycolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changenamingofSquareEnititycolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202004070840118_change naming of SquareEnitity columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
